#theme: jekyll-theme-minimal
#logo: /assets/img/lab-logo.PNG

title: CSRLab github
author:
  name: Teplitsa
 
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md
 - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

encoding: UTF-8
