# ----
# Site

title: CSRLab Teplitsa
url: "https://teplitsa.github.io/CSRLab/"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /lab-logo.PNG
description: Analytics for Teplitsa Civil Society Research Lab
author:
  name: Teplitsa
  email:
  twitter: # twitter username without the @ symbol
social:
  name: CSRLab
  links:
    - https://github.com/Teplitsa/CSRLab/

# -----
# Build

#timezone: Etc/UTC

#emoji:
#  src: "https://github.githubassets.com/images/icons/"

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
#  - jekyll-emoji
#  - jemoji
#  - jekyll/tzinfo

#emoji:
#  format: emojione-svg # default html
#  ascii: true # default false
#  shortname: true # default true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major