source 'https://rubygems.org'

gem 'jekyll', '>=3.9', '<4'
gem 'kramdown', '>= 2.3.1'
gem 'kramdown-parser-gfm'

group :jekyll_plugins do
  gem 'jekyll-feed', '0.11.0'
  gem 'jekyll-seo-tag', '2.5.0'
  gem 'jekyll-sitemap', '1.2.0'
end
